test

diff --git a/.github/workflows/CompileWindows.yml b/.github/workflows/CompileWindows.yml
--- a/.github/workflows/CompileWindows.yml
+++ b/.github/workflows/CompileWindows.yml
@@ -152,11 +152,31 @@ jobs:
         echo "------------------------------------------------------------"
         ./SHELL.sh -c '( echo stdout ; echo stderr >&2 ) | tee /dev/stderr >/dev/null || true' || true
 
+
+cat <<'EOF' > _test_PATH.sh
+function _test_PATH() {(
+    set -x
+    set +e
+    echo "BASH_SOURCE=${BASH_SOURCE[@]}"
+    echo "PATH=$PATH"
+    echo "BASH=$(/usr/bin/cygpath -ma "$BASH")"
+
+    ls -l /usr/bin/envsubst.exe || true
+    which envsubst || exit 58
+
+    echo 'key=$value' | env ${fsversionvalues[@]} envsubst '$value' || return `_err $? "_test_PATH failed"`    
+)}
+EOF
+;
+
         # while read name ; do mv -v "$name" "${name/.exe/.orig.exe}" ; done < <(/c/Windows/system32/where.exe hostname.exe tee.exe | tr -d '\r' | tr '\\' '/')
         exit 0
 
     - name: SHELL.sh test 0
       run: echo "${BASH_SOURCE[@]}"
+
+    - name: SHELL.sh test 1
+      run: $_workspace/_test_PATH.sh
 
     - name: SHELL.sh test
       run: $_workspace/SHELL.sh.test.sh
