ReleaseFS_open devtime testing

diff --git a/.github/workflows/ReleaseFS_open.yml b/.github/workflows/ReleaseFS_open.yml
--- a/.github/workflows/ReleaseFS_open.yml
+++ b/.github/workflows/ReleaseFS_open.yml
@@ -17,20 +17,35 @@ jobs:
   build:
     runs-on: windows-latest
     steps:
-      - name: Checkout code
+      - name: Checkout Viewer
         uses: actions/checkout@v5
         with:
-          fetch-depth: 0
           repository: FirestormViewer/phoenix-firestorm
           ref: ${{ inputs.ref }}
+          fetch-depth: 0         # request "all" commits...
+          filter: tree:0         # ...BUT don't download trees or file blobs for them!
+          path: .
+
+      - name: Checkout tpv-gha-nunja
+        uses: actions/checkout@v5
+        with:
+          fetch-depth: 1
+          repository: humbletim/firestorm-gha
+          ref: tpv-gha-nunja
+          path: tpv-gha-nunja
+
+      - name: Checkout p373r-vrmod
+        uses: actions/checkout@v5
+        with:
+          fetch-depth: 1
+          repository: humbletim/p373r-vrmod
+          ref: main
+          path: p373r-vrmod-main
 
       - name: Set up Python
         uses: actions/setup-python@v6
         with:
           python-version: '3.11'
-
-      - name: Install NSIS
-        run: choco install nsis
 
       - name: Install autobuild dependencies
         run: pip install -r requirements.txt
@@ -41,9 +56,31 @@ jobs:
           echo "AUTOBUILD_VARIABLES_FILE=$PWD/build-variables/variables" >> $GITHUB_ENV
           echo "AUTOBUILD_VSVER=170" >> $GITHUB_ENV
 
+      - name: Provision 3p-openvr
+          set -Euo pipefail
+          source p373r-vrmod-main/misc/3p-openvr/improvise.bash
+          provision_openvr .
+          autobuild installables edit --archive openvr-v?.?.?.*.tar.bz2
+
+      - name: Provision 3p-p373r-vrmod
+          set -Euo pipefail
+          source p373r-vrmod-main/misc/3p-p373r-vrmod/improvise.bash
+          provision_p373r_vrmod .
+          autobuild installables edit --archive p373r-vrmod-v?.?.?.*.tar.bz2
+
+      - name: Install NSIS
+        run: choco install nsis
+
       - name: Configure (open source build)
         run: |
           autobuild configure -A 64 -c ReleaseFS_open -- --package -DLL_TESTS:BOOL=FALSE
+
+      - name: ~Setup tmate session
+        if: always()
+        # if: (failure() && inputs.pause != 'never') || inputs.pause == 'always'
+        uses: mxschmitt/action-tmate@v3
+        with:
+          limit-access-to-actor: true
 
       - name: Build
         run: |
